use Customer_bhevior 

select * from [dbo].[customer]

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased, 
    AVG(review_rating) AS [Review_Product_Rating]
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
AVG(purchase_amount) as 'Avg_Amount'
from customer
where shipping_type in ('standard','express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
avg(purchase_amount) as avg_spend,
sum (purchase_amount) as total_revenu
from customer
group by subscription_status
order by  total_revenu,avg_spend desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select Top 5
	item_purchased,
	100* sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
case
	 when previous_purchases = 1 then 'New'
	 when previous_purchases  between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment
from customer
)
select customer_segment, count(*) as [number of customer]
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank >= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group,
	sum(purchase_amount) as Total_revenue
from customer
group by age_group
order by Total_revenue desc